"""
Pydantic Models for Request/Response Validation

This module defines Pydantic schemas for validating incoming requests and outgoing responses
in the AI Service. Pydantic provides automatic validation, serialization, and documentation
for FastAPI endpoints.

Design Decision: Use Pydantic for schema validation to ensure:
1. Type safety - All fields are validated against their declared types
2. Automatic API documentation - FastAPI generates OpenAPI docs from these schemas
3. Clear error messages - Pydantic provides detailed validation errors
4. Serialization/deserialization - Automatic JSON conversion with validation

Architecture:
- PromptRequest: Validates incoming prompt requests from Node.js backend
- PromptResponse: Structures successful AI responses returned to backend
- ErrorResponse: Structures error responses with detailed error information

These schemas enforce the API contract between the Node.js backend and Python AI service,
ensuring consistent data structures and preventing invalid data from propagating through
the system.
"""

from pydantic import BaseModel, Field
from typing import Optional


class PromptRequest(BaseModel):
    """
    Schema for incoming prompt requests from the Node.js backend.
    
    This schema validates that:
    1. prompt is a non-empty string with reasonable length constraints
    2. request_id is provided for request tracing across services
    
    Design Decision: Validation happens at multiple layers:
    - Backend validates prompt before calling AI service (empty, whitespace, >10000 chars)
    - This schema provides a secondary validation layer for API contract enforcement
    - request_id enables distributed tracing and correlating logs across services
    
    Fields:
        prompt: The text prompt to be processed by the AI service
                - Must be non-empty (min_length=1)
                - Must not exceed 10,000 characters (max_length=10000)
                - Whitespace-only prompts are technically valid here (backend handles this)
        request_id: Unique identifier for tracing this request across services
                    - Used for correlating logs between Node backend and Python AI service
                    - Generated by the Node backend before calling this service
    """
    prompt: str = Field(
        ...,
        min_length=1,
        max_length=10000,
        description="Text prompt to be processed by the AI service"
    )
    request_id: str = Field(
        ...,
        min_length=1,
        description="Unique identifier for request tracing"
    )


class PromptResponse(BaseModel):
    """
    Schema for successful AI responses returned to the Node.js backend.
    
    This schema structures the response from the Groq API after successful prompt processing.
    It provides all necessary information for the backend to store in the ResponseRecord
    and return to the client.
    
    Design Decision: Include model and tokens_used for monitoring and analytics:
    - model: Enables tracking which Groq model was used (useful for A/B testing, cost analysis)
    - tokens_used: Critical for cost monitoring and rate limit tracking
    - response: The actual AI-generated text that answers the user's prompt
    
    These fields enable the backend to:
    1. Store complete response metadata in the database
    2. Track token usage for billing and rate limit management
    3. Analyze which models perform best for different prompt types
    4. Provide transparency to clients about which model generated the response
    
    Fields:
        response: The AI-generated text response from the Groq API
                  - Contains the actual answer to the user's prompt
                  - Can be empty string if Groq returns empty response (rare)
        model: The Groq model identifier that processed the prompt
               - Examples: "mixtral-8x7b-32768", "llama2-70b-4096"
               - Used for analytics and debugging
        tokens_used: Total number of tokens consumed by this request
                     - Includes both prompt tokens and completion tokens
                     - Used for cost tracking and rate limit monitoring
                     - Must be non-negative integer
    """
    response: str = Field(
        ...,
        description="AI-generated text response from the Groq API"
    )
    model: str = Field(
        ...,
        min_length=1,
        description="Groq model identifier that processed the prompt"
    )
    tokens_used: int = Field(
        ...,
        ge=0,
        description="Total tokens consumed (prompt + completion)"
    )


class ErrorResponse(BaseModel):
    """
    Schema for error responses returned to the Node.js backend.
    
    This schema structures error information when the AI service encounters failures
    during prompt processing. It provides detailed error context to help the backend
    decide whether to retry, log the failure, and inform the client appropriately.
    
    Design Decision: Structured error responses enable intelligent error handling:
    - error_type: Categorizes errors for different handling strategies
    - retry_after: Provides backoff guidance for transient failures
    - status_code: Maps to HTTP status codes for consistent API behavior
    - error: Human-readable message for logging and debugging
    
    Error Types:
    - timeout: Request to Groq API exceeded time limit
    - rate_limit: Groq API rate limit exceeded (429 status)
    - network: Network connectivity issues (DNS, connection refused, etc.)
    - api_error: Groq API returned an error (4xx/5xx responses)
    - unknown: Unexpected errors that don't fit other categories
    
    The backend uses this information to:
    1. Determine if retry is appropriate (transient vs permanent failures)
    2. Log failures with proper categorization in FailureLog collection
    3. Return appropriate HTTP status codes to clients
    4. Implement exponential backoff using retry_after suggestions
    
    Fields:
        error: Human-readable error message describing what went wrong
               - Used for logging and debugging
               - Should not expose sensitive internal details to clients
        error_type: Category of error for handling logic
                    - Valid values: timeout, rate_limit, network, api_error, unknown
                    - Determines retry strategy and logging behavior
        retry_after: Suggested delay in seconds before retrying
                     - 0 means no retry recommended (permanent failure)
                     - >0 provides backoff guidance for transient failures
                     - Must be non-negative integer
        status_code: HTTP status code to return to the client
                     - Maps error to appropriate HTTP semantics
                     - Examples: 408 (timeout), 429 (rate limit), 502 (bad gateway)
                     - Must be valid HTTP status code (100-599)
    """
    error: str = Field(
        ...,
        min_length=1,
        description="Human-readable error message"
    )
    error_type: str = Field(
        ...,
        min_length=1,
        description="Error category: timeout, rate_limit, network, api_error, unknown"
    )
    retry_after: int = Field(
        ...,
        ge=0,
        description="Suggested delay in seconds before retry (0 = no retry)"
    )
    status_code: int = Field(
        ...,
        ge=100,
        le=599,
        description="HTTP status code for this error"
    )
