"""Pydantic schemas for the AI service API contract."""

from pydantic import BaseModel, Field


class PromptRequest(BaseModel):
    """Incoming prompt from the Node.js backend."""
    prompt: str = Field(..., min_length=1, max_length=10000)
    request_id: str = Field(..., min_length=1, description="Trace ID generated by the backend")


class PromptResponse(BaseModel):
    """Successful response from the Groq API."""
    response: str
    model: str
    tokens_used: int = Field(..., ge=0)


class ErrorResponse(BaseModel):
    """
    Structured error returned to the backend on failure.

    error_type drives the backend's retry decision:
      - timeout / rate_limit / network → retryable
      - api_error / unknown            → not retried
    """
    error: str
    error_type: str = Field(..., description="timeout | rate_limit | network | api_error | unknown")
    retry_after: int = Field(..., ge=0, description="Suggested seconds to wait before retry (0 = don't retry)")
    status_code: int = Field(..., ge=100, le=599)
